project:
  type: website
  output-dir: docs

website:
  title: "Quarto Template"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
      - icon: moon
        toggle: light-dark


format:
  html:
    theme:
      light: [litera, styles.scss]
      dark: [litera, styles-dark.scss]
    highlight-style: a11y-dark
    mainfont: "Roboto"
    code-copy: true
    code-overflow: wrap


execute:
  freeze: auto